
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.03 EDK_K_SP3.6
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/


/* Definitions for peripheral DNEPR */
#define XPAR_DNEPR_BASEADDR 0x30000000
#define XPAR_DNEPR_HIGHADDR 0x300000FF


/* Definitions for peripheral GRID_GEN */
#define XPAR_GRID_GEN_BASEADDR 0x20000000
#define XPAR_GRID_GEN_HIGHADDR 0x200000FF


/* Definitions for peripheral DELAY_METER */
#define XPAR_DELAY_METER_BASEADDR 0x10000000
#define XPAR_DELAY_METER_HIGHADDR 0x100003FF


/* Definitions for peripheral OPB_FLASH */
#define XPAR_OPB_FLASH_FL0_BASEADDR 0xCC000000
#define XPAR_OPB_FLASH_FL0_HIGHADDR 0xCFFFFFFF
#define XPAR_OPB_FLASH_FL1_BASEADDR 0xD0000000
#define XPAR_OPB_FLASH_FL1_HIGHADDR 0xD3FFFFFF
#define XPAR_OPB_FLASH_FL2_BASEADDR 0xD4000000
#define XPAR_OPB_FLASH_FL2_HIGHADDR 0xD7FFFFFF
#define XPAR_OPB_FLASH_FL3_BASEADDR 0xD8000000
#define XPAR_OPB_FLASH_FL3_HIGHADDR 0xDBFFFFFF


/******************************************************************/

/* Definitions for driver OPBARB */
#define XPAR_XOPBARB_NUM_INSTANCES 1

/* Definitions for peripheral OPB */
#define XPAR_OPB_BASEADDR 0xFFFFFFFF
#define XPAR_OPB_HIGHADDR 0x00000000
#define XPAR_OPB_DEVICE_ID 0
#define XPAR_OPB_NUM_MASTERS 1


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 6
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_USE_DCR 0
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral OPB_INTC_0 */
#define XPAR_OPB_INTC_0_DEVICE_ID 0
#define XPAR_OPB_INTC_0_BASEADDR 0xFE030000
#define XPAR_OPB_INTC_0_HIGHADDR 0xFE030FFF
#define XPAR_OPB_INTC_0_KIND_OF_INTR 0x0000003C


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0xFE030000
#define XPAR_INTC_SINGLE_HIGHADDR 0xFE030FFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_PLB_ETH1_CONTR_IP2INTC_IRPT_MASK 0X000001
#define XPAR_OPB_INTC_0_PLB_ETH1_CONTR_IP2INTC_IRPT_INTR 0
#define XPAR_PLB_ETH2_CONTR_IP2INTC_IRPT_MASK 0X000002
#define XPAR_OPB_INTC_0_PLB_ETH2_CONTR_IP2INTC_IRPT_INTR 1
#define XPAR_RS232_1_INTERRUPT_MASK 0X000004
#define XPAR_OPB_INTC_0_RS232_1_INTERRUPT_INTR 2
#define XPAR_RS232_2_INTERRUPT_MASK 0X000008
#define XPAR_OPB_INTC_0_RS232_2_INTERRUPT_INTR 3
#define XPAR_UART_TUTS_INTERRUPT_MASK 0X000010
#define XPAR_OPB_INTC_0_UART_TUTS_INTERRUPT_INTR 4
#define XPAR_FT_FD_INPUT_FT_INT_MASK 0X000020
#define XPAR_OPB_INTC_0_FT_FD_INPUT_FT_INT_INTR 5

/******************************************************************/


/* Canonical definitions for peripheral OPB_INTC_0 */
#define XPAR_INTC_0_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0xFE030000
#define XPAR_INTC_0_HIGHADDR 0xFE030FFF
#define XPAR_INTC_0_KIND_OF_INTR 0x0000003C

#define XPAR_INTC_0_EMAC_1_VEC_ID XPAR_OPB_INTC_0_PLB_ETH1_CONTR_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_EMAC_0_VEC_ID XPAR_OPB_INTC_0_PLB_ETH2_CONTR_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_UARTLITE_1_VEC_ID XPAR_OPB_INTC_0_RS232_1_INTERRUPT_INTR
#define XPAR_INTC_0_UARTLITE_2_VEC_ID XPAR_OPB_INTC_0_RS232_2_INTERRUPT_INTR
#define XPAR_INTC_0_UARTLITE_0_VEC_ID XPAR_OPB_INTC_0_UART_TUTS_INTERRUPT_INTR

/******************************************************************/


/* Definitions for peripheral BOOT_PPC_CNTRL */
#define XPAR_BOOT_PPC_CNTRL_BASEADDR 0xFFFF0000
#define XPAR_BOOT_PPC_CNTRL_HIGHADDR 0xFFFFFFFF


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 3

/* Definitions for peripheral UART_TUTS */
#define XPAR_UART_TUTS_BASEADDR 0xFE040000
#define XPAR_UART_TUTS_HIGHADDR 0xFE040FFF
#define XPAR_UART_TUTS_DEVICE_ID 0
#define XPAR_UART_TUTS_BAUDRATE 115200
#define XPAR_UART_TUTS_USE_PARITY 0
#define XPAR_UART_TUTS_ODD_PARITY 1
#define XPAR_UART_TUTS_DATA_BITS 8


/* Definitions for peripheral RS232_1 */
#define XPAR_RS232_1_BASEADDR 0xFE010000
#define XPAR_RS232_1_HIGHADDR 0xFE010FFF
#define XPAR_RS232_1_DEVICE_ID 1
#define XPAR_RS232_1_BAUDRATE 115200
#define XPAR_RS232_1_USE_PARITY 0
#define XPAR_RS232_1_ODD_PARITY 1
#define XPAR_RS232_1_DATA_BITS 8


/* Definitions for peripheral RS232_2 */
#define XPAR_RS232_2_BASEADDR 0xFE020000
#define XPAR_RS232_2_HIGHADDR 0xFE020FFF
#define XPAR_RS232_2_DEVICE_ID 2
#define XPAR_RS232_2_BAUDRATE 115200
#define XPAR_RS232_2_USE_PARITY 0
#define XPAR_RS232_2_ODD_PARITY 1
#define XPAR_RS232_2_DATA_BITS 8


/******************************************************************/


/* Canonical definitions for peripheral UART_TUTS */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_UART_TUTS_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0xFE040000
#define XPAR_UARTLITE_0_HIGHADDR 0xFE040FFF
#define XPAR_UARTLITE_0_BAUDRATE 115200
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 1
#define XPAR_UARTLITE_0_DATA_BITS 8
#define XPAR_UARTLITE_0_SIO_CHAN -1


/* Canonical definitions for peripheral RS232_1 */
#define XPAR_UARTLITE_1_DEVICE_ID XPAR_RS232_1_DEVICE_ID
#define XPAR_UARTLITE_1_BASEADDR 0xFE010000
#define XPAR_UARTLITE_1_HIGHADDR 0xFE010FFF
#define XPAR_UARTLITE_1_BAUDRATE 115200
#define XPAR_UARTLITE_1_USE_PARITY 0
#define XPAR_UARTLITE_1_ODD_PARITY 1
#define XPAR_UARTLITE_1_DATA_BITS 8
#define XPAR_UARTLITE_1_SIO_CHAN 0


/* Canonical definitions for peripheral RS232_2 */
#define XPAR_UARTLITE_2_DEVICE_ID XPAR_RS232_2_DEVICE_ID
#define XPAR_UARTLITE_2_BASEADDR 0xFE020000
#define XPAR_UARTLITE_2_HIGHADDR 0xFE020FFF
#define XPAR_UARTLITE_2_BAUDRATE 115200
#define XPAR_UARTLITE_2_USE_PARITY 0
#define XPAR_UARTLITE_2_ODD_PARITY 1
#define XPAR_UARTLITE_2_DATA_BITS 8
#define XPAR_UARTLITE_2_SIO_CHAN 1


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral GPIO_LEDS */
#define XPAR_GPIO_LEDS_BASEADDR 0xE0000000
#define XPAR_GPIO_LEDS_HIGHADDR 0xE0000FFF
#define XPAR_GPIO_LEDS_DEVICE_ID 0
#define XPAR_GPIO_LEDS_INTERRUPT_PRESENT 0
#define XPAR_GPIO_LEDS_IS_DUAL 0


/* Definitions for peripheral FREQ_DETECT */
#define XPAR_FREQ_DETECT_BASEADDR 0xE0001000
#define XPAR_FREQ_DETECT_HIGHADDR 0xE0001FFF
#define XPAR_FREQ_DETECT_DEVICE_ID 1
#define XPAR_FREQ_DETECT_INTERRUPT_PRESENT 0
#define XPAR_FREQ_DETECT_IS_DUAL 0


/******************************************************************/

/* Definitions for driver EMAC */
#define XPAR_XEMAC_NUM_INSTANCES 2

/* Definitions for peripheral PLB_ETH2_CONTR */
#define XPAR_PLB_ETH2_CONTR_BASEADDR 0x0B000000
#define XPAR_PLB_ETH2_CONTR_HIGHADDR 0x0B00FFFF
#define XPAR_PLB_ETH2_CONTR_DEVICE_ID 0
#define XPAR_PLB_ETH2_CONTR_ERR_COUNT_EXIST 1
#define XPAR_PLB_ETH2_CONTR_DMA_PRESENT 3
#define XPAR_PLB_ETH2_CONTR_MII_EXIST 1


/* Definitions for peripheral PLB_ETH1_CONTR */
#define XPAR_PLB_ETH1_CONTR_BASEADDR 0x0A000000
#define XPAR_PLB_ETH1_CONTR_HIGHADDR 0x0A00FFFF
#define XPAR_PLB_ETH1_CONTR_DEVICE_ID 1
#define XPAR_PLB_ETH1_CONTR_ERR_COUNT_EXIST 1
#define XPAR_PLB_ETH1_CONTR_DMA_PRESENT 3
#define XPAR_PLB_ETH1_CONTR_MII_EXIST 1


/******************************************************************/

/* Definitions for driver DDR */
#define XPAR_XDDR_NUM_INSTANCES 1

/* Definitions for peripheral PLB_DDR_SDRAM */
#define XPAR_PLB_DDR_SDRAM_ECC_BASEADDR 0xFFFFFFFF
#define XPAR_PLB_DDR_SDRAM_ECC_HIGHADDR 0x00000000
#define XPAR_PLB_DDR_SDRAM_DEVICE_ID 0
#define XPAR_PLB_DDR_SDRAM_INCLUDE_ECC_INTR 0


/******************************************************************/

/* Definitions for peripheral PLB_DDR_SDRAM */
#define XPAR_PLB_DDR_SDRAM_MEM0_BASEADDR 0x00000000
#define XPAR_PLB_DDR_SDRAM_MEM0_HIGHADDR 0x07FFFFFF

/******************************************************************/

/* Definitions for driver PLB34_REG_VERSION */
#define XPAR_PLB34_REG_VERSION_NUM_INSTANCES 1

/* Definitions for peripheral REG_VERSION */
#define XPAR_REG_VERSION_DEVICE_ID 0
#define XPAR_REG_VERSION_BASEADDR 0x0D000000
#define XPAR_REG_VERSION_HIGHADDR 0x0D00000F


/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 400000000

/******************************************************************/

#define XPAR_CPU_ID 1
#define XPAR_PPC405_ID 1
#define XPAR_PPC405_CORE_CLOCK_FREQ_HZ 400000000
#define XPAR_PPC405_ISOCM_DCR_BASEADDR 0x00000010
#define XPAR_PPC405_ISOCM_DCR_HIGHADDR 0x00000013
#define XPAR_PPC405_DSOCM_DCR_BASEADDR 0x00000020
#define XPAR_PPC405_DSOCM_DCR_HIGHADDR 0x00000023
#define XPAR_PPC405_DISABLE_OPERAND_FORWARDING 1
#define XPAR_PPC405_DETERMINISTIC_MULT 0
#define XPAR_PPC405_MMU_ENABLE 1
#define XPAR_PPC405_DCR_RESYNC 0
#define XPAR_PPC405_HW_VER "2.00.c"

/******************************************************************/

