
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.03 EDK_K_SP3.6
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xemac.h"

/*
* The configuration table for devices
*/

XEmac_Config XEmac_ConfigTable[] =
{
	{
		XPAR_PLB_ETH2_CONTR_DEVICE_ID,
		XPAR_PLB_ETH2_CONTR_BASEADDR,
		XPAR_PLB_ETH2_CONTR_ERR_COUNT_EXIST,
		XPAR_PLB_ETH2_CONTR_DMA_PRESENT,
		XPAR_PLB_ETH2_CONTR_MII_EXIST
	},
	{
		XPAR_PLB_ETH1_CONTR_DEVICE_ID,
		XPAR_PLB_ETH1_CONTR_BASEADDR,
		XPAR_PLB_ETH1_CONTR_ERR_COUNT_EXIST,
		XPAR_PLB_ETH1_CONTR_DMA_PRESENT,
		XPAR_PLB_ETH1_CONTR_MII_EXIST
	}
};


