--------------------------------------------------------------------------------
-- This VHDL file is generated by EASE/HDL from HDL Works B.V.,
-- the 'Graphical Systems Design Tool'.
--
-- Ease 5.2 Revision 5.
-- Design library : design.
-- Host name      : ILYA.
-- User name      : .
-- Time stamp     : Thu Oct 21 23:32:52 2004.
--
-- Designed by    : 
-- Company        : HDL Works.
-- Design info    : 
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Entity declaration of 'OPB_INREG'.
-- Last modified : Wed Apr 20 02:51:12 2005.
--------------------------------------------------------------------------------


library ieee ;
use ieee.std_logic_1164.all ;

entity OPB_INREG is
  port(
    OPB_DBus         : in     std_logic_vector(0 to 31);
    OPB_RNW          : in     std_logic;
    OPB_ABus         : in     std_logic_vector(0 to 31);
    OPB_select       : in     std_logic;
    Bus2IP_ABus      : out    std_logic_vector(0 to 31);
    Bus2IP_DBus      : out    std_logic_vector(0 to 31);
    Bus2IP_AddrValid : out    std_logic;
    Bus2IP_RNW       : out    std_logic;
    OPB_Clk          : in     std_logic;
    OPB_Rst          : in     std_logic;
    C_Ack            : in     std_logic);
end entity OPB_INREG ;

--------------------------------------------------------------------------------
-- Architecture 'rtl' of 'OPB_INREG'
-- Last modified : Wed Apr 20 02:51:12 2005.
--------------------------------------------------------------------------------

architecture rtl of OPB_INREG is

signal TRIG_RST : std_logic;

begin

process(OPB_Clk)
begin
	if (OPB_Clk'event and OPB_Clk = '1') then
    	if (OPB_Rst = '1' or C_Ack = '1' or TRIG_RST = '1') then 
    			Bus2IP_DBus			<= (others =>'0');
    			Bus2IP_AddrValid	<= '0';
    			Bus2IP_RNW          <= '0';
    			Bus2IP_ABus			<= (others =>'0');
    		else 
    			Bus2IP_DBus			<= OPB_DBus;
    			Bus2IP_AddrValid	<= OPB_select;
    			Bus2IP_RNW          <= OPB_RNW;
    			Bus2IP_ABus			<= OPB_ABus;
    	end if;
    end if;
end process;

process(OPB_Clk)
begin
	if OPB_Clk'event and OPB_Clk = '1' then
    	if OPB_Rst = '1' then
    		TRIG_RST <= '0';
       	else
       		TRIG_RST <= C_Ack;		
    	end if;
    end if;
end process;

end architecture rtl ; -- of OPB_INREG
