
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.03 EDK_K_SP3.6
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_UART_TUTS_DEVICE_ID,
		XPAR_UART_TUTS_BASEADDR,
		XPAR_UART_TUTS_BAUDRATE,
		XPAR_UART_TUTS_USE_PARITY,
		XPAR_UART_TUTS_ODD_PARITY,
		XPAR_UART_TUTS_DATA_BITS
	},
	{
		XPAR_RS232_1_DEVICE_ID,
		XPAR_RS232_1_BASEADDR,
		XPAR_RS232_1_BAUDRATE,
		XPAR_RS232_1_USE_PARITY,
		XPAR_RS232_1_ODD_PARITY,
		XPAR_RS232_1_DATA_BITS
	},
	{
		XPAR_RS232_2_DEVICE_ID,
		XPAR_RS232_2_BASEADDR,
		XPAR_RS232_2_BAUDRATE,
		XPAR_RS232_2_USE_PARITY,
		XPAR_RS232_2_ODD_PARITY,
		XPAR_RS232_2_DATA_BITS
	}
};


