
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.03 EDK_K_SP3.6
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xddr.h"

/*
* The configuration table for devices
*/

XDdr_Config XDdr_ConfigTable[] =
{
	{
		XPAR_PLB_DDR_SDRAM_DEVICE_ID,
		XPAR_PLB_DDR_SDRAM_ECC_BASEADDR,
		XPAR_PLB_DDR_SDRAM_INCLUDE_ECC_INTR
	}
};


